name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: os
    attributes:
      label: Operating system
      description: What operating system are you using?
      placeholder: aarch64 ArchLinux with Linux 6.0 kernel
    validations:
      required: true
  - type: input
    id: editor-version
    attributes:
      label: NeoVim/Vim version
      description: What version of NeoVim/Vim are you using?
      placeholder: NeoVim 0.8.0
    validations:
      required: true
  - type: input
    id: coc-version
    attributes:
      label: CoC version
      description: What version of CoC are you using?
      placeholder: 0.0.82
    validations:
      required: true
  - type: dropdown
    id: discord-version
    attributes:
      label: Discord version
      description: What version of Discord are you using?
      options:
        - official
        - flatpak
        - snapstore
        - other (state it in the comment of issue)
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduce step
      description: How can this bug be re-produced?
    validations:
      required: true
  - type: textarea
    id: expected-result
    attributes:
      label: Expected result
      description: What was the expected result?
    validations:
      required: true
  - type: textarea
    id: actual-result
    attributes:
      label: Actual result
      description: What happened instead?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: Shell
