name: Continuous Integration

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  Building:
    name: Compile source code
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Restore CI Cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-12-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: yarn --ignore-scripts --frozen-lockfile

      - name: Build Code
        run: yarn build
